prometheus:
  prometheusSpec:
    retention: 5d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

grafana:
  adminPassword: shopkube-admin
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

# Forcer tous les composants sur worker3-c1
prometheus:
  prometheusSpec:
    tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule
    nodeSelector:
      role: monitoring

alertmanager:
  alertmanagerSpec:
    tolerations:
    - key: dedicated
      operator: Equal
      value: monitoring
      effect: NoSchedule
    nodeSelector:
      role: monitoring

grafana:
  tolerations:
  - key: dedicated
    operator: Equal
    value: monitoring
    effect: NoSchedule
  nodeSelector:
    role: monitoring

prometheusOperator:
  tolerations:
  - key: dedicated
    operator: Equal
    value: monitoring
    effect: NoSchedule
  nodeSelector:
    role: monitoring

kube-state-metrics:
  tolerations:
  - key: dedicated
    operator: Equal
    value: monitoring
    effect: NoSchedule
  nodeSelector:
    role: monitoring

prometheus-node-exporter:
  tolerations:
  - key: dedicated
    operator: Equal
    value: monitoring
    effect: NoSchedule
