apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kitchensink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@192.168.1.121:eric/shopkube-gitops.git
    targetRevision: main
    path: helm/kitchensink
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: legacy-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
