apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ index .Values "redis-cart" "volume" "claimName" }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
