{{- $services := list "adservice" "cartservice" "checkoutservice" "currencyservice" "emailservice" "frontend" "loadgenerator" "paymentservice" "productcatalogservice" "recommendationservice" "shippingservice" }}
{{- range $services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  labels:
    app: {{ . }}
{{- end }}
